### ISSUE TITLE
hangouts-chat-linux does not run on Fedora 29

### ISSUE THREAD

**Issue by jbijota** [wheelerlaw/hangouts-chat-linux#3]
### Description
The hangouts-chat-linux does not run on Fedora 29. Probably some library is missing in requirements.

### System info
- Nativefier version: 7.6.12
- Node.js version: 10.15.0
- Command line paramters: ./hangouts
- OS and architecture: Fedora 29, Linux 5.0.3-200.fc29.x86_64 x86_64 GNU/Linux
- Error message: ./hangouts: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

### Steps to reproduce issue
1. Download .tar archive from Release page
2. Extract .tar archive
3. Run ./hangouts

**Comment by funnelfiasco** [comment]
You need the X.Org X11 libXss runtime library (`libXScrnSaver`) installed.

**Comment by jbijota** [comment]
> You need the X.Org X11 libXss runtime library (`libXScrnSaver`) installed.

Yes, it is working now, thanks!
